language: php

php: ["5.4", "5.5", "5.6", "7.0", "hhvm", "hhvm-nightly"]

matrix:
    allow_failures: [{"php": "hhvm"}, {"php": "hhvm-nightly"}]
    fast_finish: true

env:
  global:
    - ARCHER_PUBLISH_VERSION=5.6
    - secure: "HpyXe64HFHCUsAaqD9tcxmhu1D0sCceE5RzAHEm8Y+K01TDOLgdRxz9DJkxE1WZvxF3+QepBbTx19xx72NooJ0igCUwo6f2JxSDMrdballWkxn3c5WPOAe2G0BKP2+fwoY3Iy0P/UfMjXNJoIqAXH7glX0j9GObftnWuPaxC7IM="

install:
  - ./.travis.install

script:
  - ./vendor/bin/archer travis:build
